### ISSUE TITLE
In the latest release the Models.zip doesn't contain "Face"

### ISSUE THREAD

**Issue by christianschneider89** [bkpifc/BKPMediaDetector#2]
Hello

The latest Models.zip in release v1.0.3 doesn't contain the "Face" folder.
In the release v1.0.2 the Models.zip contains this "Face" folder.

Best regards
Christian

**Comment by bkpifc** [comment]
Hi Christian
Thanks for the info - must have overlooked it, sorry for that. However, nothing changed so just use the one from the previous release. I will anyway put up version 1.0.4 (Full Windows Compatibility, bug fix relating to video processing) in the next day(s), where I will make sure to include the Face model as well.
